### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by cap10morgan**
This is for deploying WildFly to the CoreOS cluster. It works in my local dev cluster.

[Pivotal card](https://www.pivotaltracker.com/story/show/86636614)

### CODE REVIEW

**Comment by cap10morgan** [comment]
Assigning @7maples.

**Comment by 7maples** [comment]
Reviewed this with Eric. Can you please add a Readme explaining what this repo is for and how to run it? Otherwise, looks good. Thanks!

**Comment by cap10morgan** [comment]
@7maples It has such a README already. Do you want something else in it?

**Comment by cap10morgan** [comment]
FYI, this should deliver the Pivotal Card now.

**Comment by 7maples** [comment]
Sorry, we didn't see it. Confused by your branch name.

**Comment by cap10morgan** [comment]
Should we use a different naming convention for these branches?

**Comment by 7maples** [comment]
I mean, it's just that this branch was called initial-commit so I guess we expected that we were literally seeing everything that had been created so far. Which we probably shouldn't have.

**Comment by cap10morgan** [comment]
IIRC, we had decided to initialize new repos with README's and then put all actual code in a PR. But my initial-commit branch also had a slightly older revision of the README in it too. Oh, but I bet it didn't show up in the Files Changed tab. So we may just have to get used to checking master for those when creating new repos.

**Pull request merged**
